import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import React, { useEffect, useState } from "react"

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  const studentsData = props.studentsData;
  useEffect(() => {

  })
  return (
    <>
      <Head>
        <title>Grema Student Portal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}

// Fetching data from the JSON file
import fsPromises from 'fs/promises';
import path from 'path'
export async function getStaticProps() {
  const filePath = path.join(process.cwd(), 'data/students.json');
  const jsonData = await fsPromises.readFile(filePath);
  const studentsData = JSON.parse(jsonData);

  return {
    props: studentsData
  }
}